spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mobilele
    username: postgres
    password: Abcd1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
#    defer-datasource-initialization: true
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#  sql:
#    init:
#      mode: never
