spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRE_HOST:localhost}:5432/mobilele
    username: ${POSTGRE_USER:postgres}
    password: ${POSTGRE_PASSWORD:Abcd1234}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
  sql:
    init:
      mode: never

default.admin.pass: topsecret